### ISSUE TITLE
Not Respecting "Generate NuGet package on build"

### ISSUE THREAD

**Issue by Noggog** [kzu/nugetizer#22]
First off, just wanted to say thanks for the help over in issue https://github.com/kzu/GitInfo/issues/134

When swapping over to Nugetizer, it was able to solve the issue of parent library versioning stamps, but I'm now noticing that it doesn't seem to be respecting my Project Settings -> Package -> "Generate NuGet package on build" setting.

Is this something that Nugetizer could be adjusted to respect and fulfill?

**Comment by kzu** [comment]
Hi @Noggog, glad to see you over here too!

This is a very nice catch/bug you uncovered, thanks! Turns out that the compatibility properties are defined in a .props file (see https://github.com/kzu/nugetizer/blob/9f35e172668e1ddf05c12dada190fdac751132d7/src/NuGetizer.Tasks/NuGetizer.Compatibility.props#L18) but props are imported at the top of your project, when your custom properties aren't still available. I'll move that to targets 👍

**Comment by kzu** [comment]
Hm, actually, it's imported from targets: https://github.com/kzu/nugetizer/blob/dev/src/NuGetizer.Tasks/NuGetizer.targets#L18

Could you run a build with `/bl` from cmdline and attach it here? (make sure it doesn't have sensitive information, it's best to do it with a repro project).

Thanks!

**Comment by Noggog** [comment]
Hmm, something weird is going on.  Both from Visual Studio and command line (`dotnet build /bl`) I see that it thinks it's creating packages:
```
Microsoft (R) Build Engine version 16.7.0+7fb82e5b2 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

C:\Program Files\dotnet\sdk\3.1.403\MSBuild.dll -consoleloggerparameters:Summary -distributedlogger:Microsoft.DotNet.Tools.MSBuild.MSBuildLogger,C:\Program Files\dotnet\sdk\3.1.403\dotnet.dll*Microsoft.DotNet.Tools.MSBuild.MSBuildForwardingLogger,C:\Program Files\dotnet\sdk\3.1.403\dotnet.dll -maxcpucount -restore -verbosity:m /bl .\GitInfoTests.sln
  Determining projects to restore...
  All projects are up-to-date for restore.
  ParentLibrary -> C:\Repos\GitInfoTests\ParentLibrary\bin\Debug\netstandard2.0\ParentLibrary.dll
  Created package at C:\Repos\GitInfoTests\ParentLibrary\bin\Debug\ParentLibrary.0.5.5.1-dev.nupkg.
  GitInfoTests -> C:\Repos\GitInfoTests\GitInfoTests\bin\Debug\netstandard2.0\GitInfoTests.dll
  Created package at C:\Repos\GitInfoTests\GitInfoTests\bin\Debug\GitInfoTests.0.5.5.1-dev.nupkg.
```

But they aren't there when I go look
![image](https://user-images.githubusercontent.com/24981326/96937433-f3941300-147c-11eb-9493-4d161a757b61.png)

Maybe they are being made, but then just cleaned up and deleted right after for somehow?

I'm just using my example repo from before:
https://github.com/Noggog/GitInfoTests

**Comment by kzu** [comment]
![image](https://user-images.githubusercontent.com/169707/97098923-534b1380-1661-11eb-8355-4c6318da090c.png)

cloned, run `msbuild -r` and sure enough, I did get the package. Opened the file and it has the right stuff in there and everything 😕

**Comment by Noggog** [comment]
Hmm, I've been running `dotnet build` not any `msbuild`.  Might that be a difference that matters?

This is my overall behavior.  You can see my `dotnet build` has no output, but `dotnet pack` does.

https://i.imgur.com/LMNn5iL.mp4

I cloned to a 2nd machine (my laptop) and got the same behavior.

Additionally, I made the changes we did to the GitInfoTests repo to one of my other projects, and had some strange behavior.  The presence of Nugetizer made the "Package" option in the project panel disappear entirely.  Removing Nugetizer brings it back,   This behavior hasn't occurred in GitInfoTests yet that I've seen.

https://i.imgur.com/GnAKziw.mp4

**Comment by kzu** [comment]
Without binlogs, it's really hard to know what's going on.

**Comment by kzu** [comment]
a-ha, the binlog reveals the issue indeed 👍 

![image](https://user-images.githubusercontent.com/169707/97524715-1abe7900-1984-11eb-942c-18998d1452c7.png)

Seems like a bug I introduced with the output cleanup. For now you can workaround it by setting `EnablePackCleanup=false` in your project.

**Comment by kzu** [comment]
ok, was a bug, here's a binlog where it's fixed now :) 
[msbuild.zip](https://github.com/kzu/nugetizer/files/5456163/msbuild.zip)

**Comment by Noggog** [comment]
Heyyy!  Got things working!  Thanks for the help investigating

**Comment by kzu** [comment]
Thanks for uncovering the bug and helping verify the fix! 💯
