### ISSUE TITLE
Multitarget Issues

### ISSUE THREAD

**Issue by Noggog** [kzu/nugetizer#27]
With the release of .NET5, I've been trying to do some multitargeting by having my libraries target both .NET5 and .net standard 2.1.

I have a solution with two libraries.
One is netstandard2.1.  The other depends on the first and is netcore3.1.

Both compile and work fine as described above, and also if both are upgraded to net5.0.

The issue comes up when i multitarget /w `<TargetFrameworks>net5.0;netstandard2.1</TargetFrameworks>`, for example.

The first library works and compiles fine.  The second fails with this error:

```
Some project references cannot be properly packaged. 
Please install the NuGetizer package on the following projects: 
..\TheParentProject\TheParentProject.csproj
```

Not 100% certain it's not user error on my side, but I figured I'd see if you saw similar results

**Comment by kzu** [comment]
You must install nugetizer in all projects involved in a pack operation. Do you have it installed in `TheParentProject.csproj`, as requested in the error message?

**Comment by Noggog** [comment]
Yeah, I have the latest nugetizer installed via NuGet on all projects in my solution.  The error complains that it's not installed on the parent project, but that is not the case (afaik)

**Comment by kzu** [comment]
Could you please attach a repro project with a binlog too?

Thanks!

**Comment by Noggog** [comment]
Went to set up the example project, but it looks like it got fixed in the 0.5 release.  Thanks!

**Comment by Noggog** [comment]
As mentioned in #34 , I think this is still an issue now that I look closer.  I think 5.0 just broke the "pack on build" feature, which made it look like this issue went away (because it was never trying to build -> didn't fail)

**Comment by Noggog** [comment]
Updated https://github.com/Noggog/GitInfoTests to contain an example of what I'm seeing:
1)  Pack on build isn't working, so you have to run `dotnet pack` at the solution level to see the error
2)  It only seems to bite after adding that wpf library project?  Might be some difference between that project and the simpler GitInfoTests library?

**Comment by kzu** [comment]
Oh boy, what a trip down the rabbit hole that was! 

I added a repro project and used that to implement the fix, so things should be working as soon as I cut a new release. You can use the CI feed/package in the meantime.

I did find a minor issue with your projects: you had `net5` as the target framework, but I think they should be `net5.0`. Not sure if that was one more of the underlying issues, but with the latter, things work as expected now :)

Thanks again for your patience and for providing a clear repro and putting in the time to explain to me what was going on and what alternatives you tried. It was super helpful and uncovered a tricky issue! 💯

**Comment by Noggog** [comment]
> I did find a minor issue with your projects: you had `net5` as the target framework, but I think they should be `net5.0`. Not sure if that was one more of the underlying issues, but with the latter, things work as expected now :)

Ah!  Will tinker and see if that was causing me any issues.  My feeling is that it's been picking up and been okay in vanilla VS with `net5` specified.

> Thanks again for your patience and for providing a clear repro and putting in the time to explain to me what was going on and what alternatives you tried. It was super helpful and uncovered a tricky issue! 💯

No problem!  I know I appreciate people doing the same.  8)

**Comment by kzu** [comment]
New version pushed now!
