### ISSUE TITLE
Multitargeting => No auto nuget package creation

### ISSUE THREAD

**Issue by Noggog** [kzu/nugetizer#34]
If I go to multiple target frameworks, it no longer produces a nuget package.  I am able to get one with an explicit `dotnet pack`, but not the automatic one after building.  If I knock my project back to a single framework target, it creates a nuget package on build as expected.

**Comment by Noggog** [comment]
I have the bad feeling that my "fix" for #27 was actually this issue.  I think 5.0 is just not packing on build, which means it didn't trigger the failure from #27

**Comment by kzu** [comment]
This is weird because I have a unit test that exercises this very same feature: https://github.com/kzu/nugetizer/blob/main/src/NuGetizer.Tests/InlineProjectTests.cs#L442

Could you attach a binlog and a small repro? Thanks!

**Comment by Noggog** [comment]
Sure!  I've just been pushing changes to my same old repo:
https://github.com/Noggog/GitInfoTests
When I open this solution in visual studio, clear out the old build artifacts, and build fresh, I don't see any nuget package produced.  If I swap the TargetFramework to just be a single, it starts producing the package again.

Here is the bl from the GitInfoTests project build:
```
PS C:\Repos\GitInfoTests\GitInfoTests> dotnet build /bl
Microsoft (R) Build Engine version 16.8.0+126527ff1 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

C:\Program Files\dotnet\sdk\5.0.100\MSBuild.dll -consoleloggerparameters:Summary -distributedlogger:Microsoft.DotNet.Tools.MSBuild.MSBuildLogger,C:\Program Files\dotnet\sdk\5.0.100\dotnet.dll*Microsoft.DotNet.Tools.MSBuild.MSBuildForwardingLogger,C:\Program Files\dotnet\sdk\5.0.100\dotnet.dll -maxcpucount -restore -verbosity:m /bl .\GitInfoTests.csproj
  Determining projects to restore...
  Restored C:\Repos\GitInfoTests\GitInfoTests\GitInfoTests.csproj (in 86 ms).
  1 of 2 projects are up-to-date for restore.
  ParentLibrary -> C:\Repos\GitInfoTests\ParentLibrary\bin\Debug\net5\ParentLibrary.dll
  ParentLibrary -> C:\Repos\GitInfoTests\ParentLibrary\bin\Debug\netstandard2.1\ParentLibrary.dll
  GitInfoTests -> C:\Repos\GitInfoTests\GitInfoTests\bin\Debug\netstandard2.1\GitInfoTests.dll
  GitInfoTests -> C:\Repos\GitInfoTests\GitInfoTests\bin\Debug\net5\GitInfoTests.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

```

**Comment by kzu** [comment]
gotcha, checking it out, tnx!

**Comment by kzu** [comment]
(FWIW, "attaching the binlog" means that you should grab the `msbuild.binlog` file generated after you run `msbuild /tb` zip it up and drop it here on the issue so I can look at the entire build in detail 😉)

**Comment by kzu** [comment]
This was a tricky one to find, thanks a lot for reporting and bearing with me! 

It was a combination of the multi-targeting and the fact that you're using `GeneratePackageOnBuild` (which is the SDK pack way) rather than `PackOnBuild` which is nugetizer's 🤷‍♀️.

Now that again uncovers the other issue, so I'm working on that next.

**Comment by Noggog** [comment]
> (FWIW, "attaching the binlog" means that you should grab the `msbuild.binlog` file generated after you run `msbuild /tb` zip it up and drop it here on the issue so I can look at the entire build in detail 😉)

Ah!  Good to know!  Does that file get created if running through `dotnet build`?  I never actually run `msbuild`.

**Comment by kzu** [comment]
Yes, indeed. You use `dotnet build -bl` and would get the binlog, which you can later on inspect with the awesome https://www.msbuildlog.com/
